package com.itp.jsp.WEB_002dINF.jsp.ticket;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ticket_005fdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div>\n     <table class=\"componentStyle\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\n\t<tr>\n            <td class=\"headerBox\">\n\t\t\tTicket:(ITP_041_04131)\n            </td>\n        </tr>\n\t<tr>\n            <td style=\"font-size:12px; font-family:Arial, Helvetica, sans-serif; padding:10px; vertical-align: top; \">\n                  <div style=\"width:1000\" >\n                             <table  width=\"1000\" class=\"ui-state-custom ui-corner-all\" style=\"background-color:#ffffff;\"  cellpadding=\"4\" cellspacing=\"0\" bgcolor=\"#FFFFFF\" >\n                                  <tr>\n                                      <th  width=\"25%\" align=\"left\">\n                                      </th>\n                                      <th  width=\"75%\" >\n                                      </th>\n                                  </tr>\n                                  \n                                  <tr>\n                                      <td colspan=\"2\" >\n                                            <table width=\"982px\" border=\"0\" style=\"border-bottom:solid 1px ;border-bottom-style:dashed\" >\n");
      out.write("                                                  <tr>\n                                                       <td>Ticket #:</td>\n                                                       <td width=\"21%\" ><b><span  style=\"background-color:#FFFFCC\"> (ITP_041_04131) </span></b></td>\n                                                       <td colspan=\"4\">Age:(days) Hour:(hour) Min:(min)</td>\n                                                  </tr>\n                                                  <tr>\n                                                       <td width=\"11%\">Subject:</td><td>(CFC is online)</td>\n                                                       <td width=\"8%\">Priority:</td><td width=\"20%\">(priority)</td>\n                                                       <td>Action Taken:</td><td width=\"14%\">(action)</td>\n                                                  </tr>\n                                                  <tr>\n                                                       <td>&nbsp;</td><td>&nbsp;</td>\n");
      out.write("                                                       <td>Status:</td><td>(status)</td>\n                                                       <td>Date Closed:</td><td>(date)</td>\n                                                  </tr>\n                                                  <tr >\n                                                       <td style=\"vertical-align:top; \">Summary:</td>\n                                                       \n                                                       <td colspan=\"5\">\n                                                           <div style=\" \n                                                             width:800px;\n                                                             height:350px;\n                                                             background-color:#ffffff;\n                                                             overflow:auto;\">\n\n                                                            PUT YOUR TEXT HERE<p>Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.</p>\n");
      out.write("<span><p>Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.</p></span>\n");
      out.write("                                                       \n                                                            </div>\n                                                           </td>\n                                                  </tr>\n                                            </table>\n                                            \n                                            <br/>\n                                            <div>\n                                               <table width=\"982\" style=\"border-bottom:solid 1px ;border-bottom-style:dashed\">\n                                                     <tr>\n                                                         <td width=\"95\" height=\"35\">Attachment:</td>\n                                                         <td width=\"317\" height=\"35\"></td>\n                                                         <td width=\"350\" rowspan=\"2\" class=\"ticketButton\" height=\"70\">Accept Ticket<br />Request</td>\n                                                     </tr>\n");
      out.write("                                                     <tr>\n                                                         <td colspan=\"2\" >\n                                                              <div>\n                                                                  <table cellpadding=\"2\" cellspacing=\"2\" width=\"100%\">\n                                                                       <tr>\n                                                                           <td>\n                                                                                <img src=\"");
      out.print( request.getContextPath());
      out.write("/images/attachment_icon_black.gif\" />&nbsp;&nbsp;&nbsp;&nbsp;fileName.txt&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\" class=\"blue_links\">[X]</a>\n                                                                           </td>\n                                                                       </tr>\n                                                                  </table>\n                                                              </div>\n                                                              <br/>\n                                                              <br/>\n                                            \n                                                         </td>\n                                                      </tr>\n                                               </table>\n                                            </div>\n                                            \n                                            <div>\n                                                <br/>\n                                            \n");
      out.write("                                                <table>\n                                                    <tr>\n                                                        <td width=\"47\"><input type=\"button\" value=\"Reply\" />\n                                                        <td width=\"46\"><input type=\"button\" value=\"Fixed\" />\n                                                        <td width=\"568\"><input type=\"button\" value=\"Close\" />\n                                                    </tr>\n                                                </table>\n                                            </div>\n                                       </td>\n                                  </tr>\n                           </table>\n                           \n                  </div>\n                  \n                 <br/>\n                                            \n                  <div>\n                        <table  class=\"ui-state-custom ui-corner-all\"  style=\"border-color:#ccc; background-color:#FFF \" width=\"1000\" >\n");
      out.write("\n                        <tr>\n                                <td colspan=\"3\">\n                                <table height=\"73\" border=\"0\"cellpadding=\"0\" cellspacing=\"0\">\n                                        <tr>\n                                        <td valign=\"top\">\n                                                <table>\n                                                <tr>\n                                                        <td width=\"153\" align=\"center\" style=\"vertical-align:top\"><img src=\"");
      out.print( request.getContextPath());
      out.write("/images/davidp.jpg\" alt=\"\" width=\"69\" height=\"60\" /></td>\n                                                </tr>\n                                                <tr>\n                                                        <td align=\"center\" valign=\"top\">David Pickron</td>\n                                                </tr>\n                                            </table>\n                                        </td>\n                                        <td width=\"844\">\n                                                <table cellpadding=\"1\" cellspacing=\"1\">\n                                                <tr>\n                                                        <td width=\"844\" align=\"left\" valign=\"top\" class=\"blue_links\">\n                                                            <table width=\"100%\"><tr>\n                                                              <td  width=\"50%\"><span style=\"color:#39C\">Sent:</span> Thu 6/9/2011 4:54 AM</td><td align=\"right\" width=\"50%\"><a href=\"\">delete</a></td></tr></table></td>\n");
      out.write("                                                </tr>\n\n                                                        <tr>\n                                                        <td><span><p>Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.</p></span></td>\n");
      out.write("                                                    </tr>\n\n\n                                            </table>\n\n                                        </td>\n                                    </tr>\n                                </table>\n                            </td>\n                        </tr>\n\n                                <tr style=\" border-top:thin solid #666 \">\n                                 <td width=\"73\"   valign=\"top\" style=\"padding:10px;\">Attachment:</td>\n                                 <td   valign=\"top\" style=\"padding:10px;\">\n                                   <div>\n\n                                           <img src=\"");
      out.print( request.getContextPath());
      out.write("/images/attachment_icon_black.gif\" />&nbsp;&nbsp;&nbsp;&nbsp;fileName.txt&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\" class=\"blue_links\">[X]</a>\n\n                                       </div>\n                                   </td>\n                                 <td width=\"228\" align=\"right\" valign=\"top\"  class=\"blue_links\" style=\"padding:10px\"><a href=\"\">download</a></td>\n                            </tr>\n\n                    </table>\n                    <br/><br/>\n                    <table  class=\"ui-state-custom ui-corner-all\"  style=\"border-color:#ccc; background-color:#EFEFEF\" width=\"1000\" >\n\n                        <tr>\n                                <td colspan=\"3\">\n                                <table height=\"73\" border=\"0\"cellpadding=\"0\" cellspacing=\"0\">\n                                        <tr>\n                                        <td valign=\"top\">\n                                                <table>\n                                                <tr>\n                                                    <td width=\"153\" align=\"center\" style=\"vertical-align:top;padding-top:20px\">\n");
      out.write("                                                        <span style=\"color:#39C; font-size:14px\"><b>YOU</b></span>\n                                                    </td>\n                                                </tr>\n                                                <tr>\n                                                        <td align=\"center\" valign=\"top\">&nbsp;</td>\n                                                </tr>\n                                            </table>\n                                        </td>\n                                        <td width=\"844\">\n                                                <table cellpadding=\"1\" cellspacing=\"1\">\n                                                <tr>\n                                                        <td width=\"844\" align=\"left\" valign=\"top\" class=\"blue_links\"><table width=\"100%\"><tr>\n                                                              <td  width=\"50%\"><span style=\"color:#39C\">Sent:</span> Thu 6/9/2011 4:54 AM</td><td align=\"right\" width=\"50%\"><a href=\"\">delete</a></td></tr></table></td>\n");
      out.write("                                                </tr>\n\n                                                        <tr>\n                                                        <td>\n                                                            <span><p>Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.</p></span>\n");
      out.write("                                                            <span><p>Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.Error encountered during connection.. Is there posibilities to resolve such this error in all our applications? this is just a test.</p></span>\n");
      out.write("                                                        </td>\n                                                    </tr>\n\n\n                                            </table>\n\n                                        </td>\n                                    </tr>\n                                </table>\n                            </td>\n                        </tr>\n\n                             <!--tr style=\" border-top:thin solid #666 \">\n                                 <td width=\"73\"   valign=\"top\" style=\"padding:10px;\">Attachment:</td>\n                                 <td   valign=\"top\" style=\"padding:10px;\">\n                                   <div>\n\n                                           <img src=\"< % = request.getContextPath()%>/images/attachment_icon_black.gif\" />&nbsp;&nbsp;&nbsp;&nbsp;fileName.txt&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\" class=\"blue_links\">[X]</a>\n\n                                       </div>\n                                   </td>\n                                 <td width=\"228\" align=\"right\" valign=\"top\"  class=\"blue_links\" style=\"padding:10px\"><a href=\"\">download</a></td>\n");
      out.write("                            </tr-->\n\n                    </table>\n                </div>\n                <br/>\n                <table width=\"1000\"  style=\"border-bottom:solid 1px ;border-bottom-style:dashed\"><tr><td></td></tr></table>\n                <br/>\n                                            \n                                            \n                <div>\n                    <span style=\"color:#39C; font-size:14px\"><b>Post a reply</b></span>\n                    <table style=\"border:#E1E2E3 solid 1px;padding:10px\" width=\"1000\">\n                        <tr>\n                             <td >\n                                <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n                                        <tr>\n                                        <td width=\"113\" align=\"center\" valign=\"top\">\n                                                Messages\n                                        </td>\n                                        <td width=\"638\" colspan=\"3\" valign=\"top\">\n                                               <textarea cols=\"100\" rows=\"10\"></textarea>\n");
      out.write("                                        </td>\n                                    </tr>\n                                </table>\n                            </td>       \t                \n                        </tr>\n                         <tr>\n                             <td  height=\"35\">Attachment: &nbsp;<input type=\"file\" name=\"dataFile\" size=\"25\"/></td>\n\n                        </tr>\n                        <tr>\n                             <td >\n                                 <div>\n                                      <table cellpadding=\"2\" cellspacing=\"2\" width=\"100%\">\n                                            <tr>\n                                               <td>\n                                                   <img src=\"");
      out.print( request.getContextPath());
      out.write("/images/attachment_icon_black.gif\" />&nbsp;&nbsp;&nbsp;&nbsp;fileName.txt&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\" class=\"blue_links\">[X]</a>\n                                               </td>\n                                            </tr>\n                                      </table>\n                                </div>\n                            </td>\n                        </tr>\n                        <tr>\n                            <td  align=\"right\"><input type=\"button\" value=\"Reply\" /></td>\n                        </tr>\n                    </table>\n                </div>\n            </td>\n        </tr>\n    </table>\n</div>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
