package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Asset generated by hbm2java
 */
public class Asset  implements java.io.Serializable {


     private Integer assetId;
     private Project project;
     private String assetName;
     private String assetDescription;
     private double assetCost;
     private Date dateBudgeted;
     private String userApproved;
     private Date dateApproved;

    public Asset() {
    }

	
    public Asset(Project project, String assetName, double assetCost, Date dateBudgeted, String userApproved, Date dateApproved) {
        this.project = project;
        this.assetName = assetName;
        this.assetCost = assetCost;
        this.dateBudgeted = dateBudgeted;
        this.userApproved = userApproved;
        this.dateApproved = dateApproved;
    }
    public Asset(Project project, String assetName, String assetDescription, double assetCost, Date dateBudgeted, String userApproved, Date dateApproved) {
       this.project = project;
       this.assetName = assetName;
       this.assetDescription = assetDescription;
       this.assetCost = assetCost;
       this.dateBudgeted = dateBudgeted;
       this.userApproved = userApproved;
       this.dateApproved = dateApproved;
    }
   
    public Integer getAssetId() {
        return this.assetId;
    }
    
    public void setAssetId(Integer assetId) {
        this.assetId = assetId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getAssetName() {
        return this.assetName;
    }
    
    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }
    public String getAssetDescription() {
        return this.assetDescription;
    }
    
    public void setAssetDescription(String assetDescription) {
        this.assetDescription = assetDescription;
    }
    public double getAssetCost() {
        return this.assetCost;
    }
    
    public void setAssetCost(double assetCost) {
        this.assetCost = assetCost;
    }
    public Date getDateBudgeted() {
        return this.dateBudgeted;
    }
    
    public void setDateBudgeted(Date dateBudgeted) {
        this.dateBudgeted = dateBudgeted;
    }
    public String getUserApproved() {
        return this.userApproved;
    }
    
    public void setUserApproved(String userApproved) {
        this.userApproved = userApproved;
    }
    public Date getDateApproved() {
        return this.dateApproved;
    }
    
    public void setDateApproved(Date dateApproved) {
        this.dateApproved = dateApproved;
    }




}


