package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Component generated by hbm2java
 */
public class Component  implements java.io.Serializable {


     private Integer componentId;
     private String componentName;
     private String componentDescription;
     private int componentLeadId;
     private Set<Note> notes = new HashSet<Note>(0);

    public Component() {
    }

	
    public Component(int componentLeadId) {
        this.componentLeadId = componentLeadId;
    }
    public Component(String componentName, String componentDescription, int componentLeadId, Set<Note> notes) {
       this.componentName = componentName;
       this.componentDescription = componentDescription;
       this.componentLeadId = componentLeadId;
       this.notes = notes;
    }
   
    public Integer getComponentId() {
        return this.componentId;
    }
    
    public void setComponentId(Integer componentId) {
        this.componentId = componentId;
    }
    public String getComponentName() {
        return this.componentName;
    }
    
    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }
    public String getComponentDescription() {
        return this.componentDescription;
    }
    
    public void setComponentDescription(String componentDescription) {
        this.componentDescription = componentDescription;
    }
    public int getComponentLeadId() {
        return this.componentLeadId;
    }
    
    public void setComponentLeadId(int componentLeadId) {
        this.componentLeadId = componentLeadId;
    }
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }




}


