package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer companyId;
     private String companyName;
     private String companyDescription;
     private String email;
     private String phoneNumber;
     private Set<Project> projects = new HashSet<Project>(0);

    public Company() {
    }

	
    public Company(String companyName) {
        this.companyName = companyName;
    }
    public Company(String companyName, String companyDescription, String email, String phoneNumber, Set<Project> projects) {
       this.companyName = companyName;
       this.companyDescription = companyDescription;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.projects = projects;
    }
   
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanyDescription() {
        return this.companyDescription;
    }
    
    public void setCompanyDescription(String companyDescription) {
        this.companyDescription = companyDescription;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Set<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }




}


