package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA



/**
 * Configuration generated by hbm2java
 */
public class Configuration  implements java.io.Serializable {


     private String configurationKey;
     private ConfigurationCategory configurationCategory;
     private String configurationValue;
     private String configurationDescription;

    public Configuration() {
    }

	
    public Configuration(String configurationKey, ConfigurationCategory configurationCategory) {
        this.configurationKey = configurationKey;
        this.configurationCategory = configurationCategory;
    }
    public Configuration(String configurationKey, ConfigurationCategory configurationCategory, String configurationValue, String configurationDescription) {
       this.configurationKey = configurationKey;
       this.configurationCategory = configurationCategory;
       this.configurationValue = configurationValue;
       this.configurationDescription = configurationDescription;
    }
   
    public String getConfigurationKey() {
        return this.configurationKey;
    }
    
    public void setConfigurationKey(String configurationKey) {
        this.configurationKey = configurationKey;
    }
    public ConfigurationCategory getConfigurationCategory() {
        return this.configurationCategory;
    }
    
    public void setConfigurationCategory(ConfigurationCategory configurationCategory) {
        this.configurationCategory = configurationCategory;
    }
    public String getConfigurationValue() {
        return this.configurationValue;
    }
    
    public void setConfigurationValue(String configurationValue) {
        this.configurationValue = configurationValue;
    }
    public String getConfigurationDescription() {
        return this.configurationDescription;
    }
    
    public void setConfigurationDescription(String configurationDescription) {
        this.configurationDescription = configurationDescription;
    }




}


