package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ConfigurationCategory generated by hbm2java
 */
public class ConfigurationCategory  implements java.io.Serializable {


     private Integer configurationCategoryId;
     private String configurationCategoryDefinition;
     private Set<Configuration> configurations = new HashSet<Configuration>(0);

    public ConfigurationCategory() {
    }

    public ConfigurationCategory(String configurationCategoryDefinition, Set<Configuration> configurations) {
       this.configurationCategoryDefinition = configurationCategoryDefinition;
       this.configurations = configurations;
    }
   
    public Integer getConfigurationCategoryId() {
        return this.configurationCategoryId;
    }
    
    public void setConfigurationCategoryId(Integer configurationCategoryId) {
        this.configurationCategoryId = configurationCategoryId;
    }
    public String getConfigurationCategoryDefinition() {
        return this.configurationCategoryDefinition;
    }
    
    public void setConfigurationCategoryDefinition(String configurationCategoryDefinition) {
        this.configurationCategoryDefinition = configurationCategoryDefinition;
    }
    public Set<Configuration> getConfigurations() {
        return this.configurations;
    }
    
    public void setConfigurations(Set<Configuration> configurations) {
        this.configurations = configurations;
    }




}


