package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FileRecord generated by hbm2java
 */
public class FileRecord  implements java.io.Serializable {


     private Integer fileRecordId;
     private FileRecordType fileRecordType;
     private String fileName;
     private byte[] data;
     private String webFileType;
     private Date dateTimeCreated;
     private Date dateTimeUpdated;
     private long fileByteSize;
     private Set<NoteAttachement> noteAttachements = new HashSet<NoteAttachement>(0);

    public FileRecord() {
    }

	
    public FileRecord(Date dateTimeCreated, Date dateTimeUpdated, long fileByteSize) {
        this.dateTimeCreated = dateTimeCreated;
        this.dateTimeUpdated = dateTimeUpdated;
        this.fileByteSize = fileByteSize;
    }
    public FileRecord(FileRecordType fileRecordType, String fileName, byte[] data, String webFileType, Date dateTimeCreated, Date dateTimeUpdated, long fileByteSize, Set<NoteAttachement> noteAttachements) {
       this.fileRecordType = fileRecordType;
       this.fileName = fileName;
       this.data = data;
       this.webFileType = webFileType;
       this.dateTimeCreated = dateTimeCreated;
       this.dateTimeUpdated = dateTimeUpdated;
       this.fileByteSize = fileByteSize;
       this.noteAttachements = noteAttachements;
    }
   
    public Integer getFileRecordId() {
        return this.fileRecordId;
    }
    
    public void setFileRecordId(Integer fileRecordId) {
        this.fileRecordId = fileRecordId;
    }
    public FileRecordType getFileRecordType() {
        return this.fileRecordType;
    }
    
    public void setFileRecordType(FileRecordType fileRecordType) {
        this.fileRecordType = fileRecordType;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }
    public String getWebFileType() {
        return this.webFileType;
    }
    
    public void setWebFileType(String webFileType) {
        this.webFileType = webFileType;
    }
    public Date getDateTimeCreated() {
        return this.dateTimeCreated;
    }
    
    public void setDateTimeCreated(Date dateTimeCreated) {
        this.dateTimeCreated = dateTimeCreated;
    }
    public Date getDateTimeUpdated() {
        return this.dateTimeUpdated;
    }
    
    public void setDateTimeUpdated(Date dateTimeUpdated) {
        this.dateTimeUpdated = dateTimeUpdated;
    }
    public long getFileByteSize() {
        return this.fileByteSize;
    }
    
    public void setFileByteSize(long fileByteSize) {
        this.fileByteSize = fileByteSize;
    }
    public Set<NoteAttachement> getNoteAttachements() {
        return this.noteAttachements;
    }
    
    public void setNoteAttachements(Set<NoteAttachement> noteAttachements) {
        this.noteAttachements = noteAttachements;
    }




}


