package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ItpComponent generated by hbm2java
 */
public class ItpComponent  implements java.io.Serializable {


     private Integer itpComponentId;
     private String componentName;
     private String componentDescription;
     private Set<Permission> permissions = new HashSet<Permission>(0);

    public ItpComponent() {
    }

	
    public ItpComponent(String componentName, String componentDescription) {
        this.componentName = componentName;
        this.componentDescription = componentDescription;
    }
    public ItpComponent(String componentName, String componentDescription, Set<Permission> permissions) {
       this.componentName = componentName;
       this.componentDescription = componentDescription;
       this.permissions = permissions;
    }
   
    public Integer getItpComponentId() {
        return this.itpComponentId;
    }
    
    public void setItpComponentId(Integer itpComponentId) {
        this.itpComponentId = itpComponentId;
    }
    public String getComponentName() {
        return this.componentName;
    }
    
    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }
    public String getComponentDescription() {
        return this.componentDescription;
    }
    
    public void setComponentDescription(String componentDescription) {
        this.componentDescription = componentDescription;
    }
    public Set<Permission> getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(Set<Permission> permissions) {
        this.permissions = permissions;
    }




}


