package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA



/**
 * Month generated by hbm2java
 */
public class Month  implements java.io.Serializable {


     private int monthId;
     private String monthName;
     private String monthAbbreviation;

    public Month() {
    }

    public Month(int monthId, String monthName, String monthAbbreviation) {
       this.monthId = monthId;
       this.monthName = monthName;
       this.monthAbbreviation = monthAbbreviation;
    }
   
    public int getMonthId() {
        return this.monthId;
    }
    
    public void setMonthId(int monthId) {
        this.monthId = monthId;
    }
    public String getMonthName() {
        return this.monthName;
    }
    
    public void setMonthName(String monthName) {
        this.monthName = monthName;
    }
    public String getMonthAbbreviation() {
        return this.monthAbbreviation;
    }
    
    public void setMonthAbbreviation(String monthAbbreviation) {
        this.monthAbbreviation = monthAbbreviation;
    }




}


