package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * NoteType generated by hbm2java
 */
public class NoteType  implements java.io.Serializable {


     private Integer noteTypeId;
     private String noteTypeName;
     private String noteTypeDescription;
     private Set<Note> notes = new HashSet<Note>(0);

    public NoteType() {
    }

    public NoteType(String noteTypeName, String noteTypeDescription, Set<Note> notes) {
       this.noteTypeName = noteTypeName;
       this.noteTypeDescription = noteTypeDescription;
       this.notes = notes;
    }
   
    public Integer getNoteTypeId() {
        return this.noteTypeId;
    }
    
    public void setNoteTypeId(Integer noteTypeId) {
        this.noteTypeId = noteTypeId;
    }
    public String getNoteTypeName() {
        return this.noteTypeName;
    }
    
    public void setNoteTypeName(String noteTypeName) {
        this.noteTypeName = noteTypeName;
    }
    public String getNoteTypeDescription() {
        return this.noteTypeDescription;
    }
    
    public void setNoteTypeDescription(String noteTypeDescription) {
        this.noteTypeDescription = noteTypeDescription;
    }
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }




}


