package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA



/**
 * NoteAttachement generated by hbm2java
 */
public class NoteAttachement  implements java.io.Serializable {


     private Integer noteAttachementId;
     private FileRecord fileRecord;
     private Note note;

    public NoteAttachement() {
    }

    public NoteAttachement(FileRecord fileRecord, Note note) {
       this.fileRecord = fileRecord;
       this.note = note;
    }
   
    public Integer getNoteAttachementId() {
        return this.noteAttachementId;
    }
    
    public void setNoteAttachementId(Integer noteAttachementId) {
        this.noteAttachementId = noteAttachementId;
    }
    public FileRecord getFileRecord() {
        return this.fileRecord;
    }
    
    public void setFileRecord(FileRecord fileRecord) {
        this.fileRecord = fileRecord;
    }
    public Note getNote() {
        return this.note;
    }
    
    public void setNote(Note note) {
        this.note = note;
    }




}


