package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Note generated by hbm2java
 */
public class Note  implements java.io.Serializable {


     private Integer noteId;
     private Component component;
     private User user;
     private Project project;
     private NoteType noteType;
     private Priority priority;
     private String noteSummary;
     private Date dueDate;
     private String environment;
     private String noteDescription;
     private String estimatedHours;
     private Set<NoteAttachement> noteAttachements = new HashSet<NoteAttachement>(0);

    public Note() {
    }

	
    public Note(Component component, User user, Project project, NoteType noteType, Priority priority, Date dueDate, String noteDescription, String estimatedHours) {
        this.component = component;
        this.user = user;
        this.project = project;
        this.noteType = noteType;
        this.priority = priority;
        this.dueDate = dueDate;
        this.noteDescription = noteDescription;
        this.estimatedHours = estimatedHours;
    }
    public Note(Component component, User user, Project project, NoteType noteType, Priority priority, String noteSummary, Date dueDate, String environment, String noteDescription, String estimatedHours, Set<NoteAttachement> noteAttachements) {
       this.component = component;
       this.user = user;
       this.project = project;
       this.noteType = noteType;
       this.priority = priority;
       this.noteSummary = noteSummary;
       this.dueDate = dueDate;
       this.environment = environment;
       this.noteDescription = noteDescription;
       this.estimatedHours = estimatedHours;
       this.noteAttachements = noteAttachements;
    }
   
    public Integer getNoteId() {
        return this.noteId;
    }
    
    public void setNoteId(Integer noteId) {
        this.noteId = noteId;
    }
    public Component getComponent() {
        return this.component;
    }
    
    public void setComponent(Component component) {
        this.component = component;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public NoteType getNoteType() {
        return this.noteType;
    }
    
    public void setNoteType(NoteType noteType) {
        this.noteType = noteType;
    }
    public Priority getPriority() {
        return this.priority;
    }
    
    public void setPriority(Priority priority) {
        this.priority = priority;
    }
    public String getNoteSummary() {
        return this.noteSummary;
    }
    
    public void setNoteSummary(String noteSummary) {
        this.noteSummary = noteSummary;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public String getEnvironment() {
        return this.environment;
    }
    
    public void setEnvironment(String environment) {
        this.environment = environment;
    }
    public String getNoteDescription() {
        return this.noteDescription;
    }
    
    public void setNoteDescription(String noteDescription) {
        this.noteDescription = noteDescription;
    }
    public String getEstimatedHours() {
        return this.estimatedHours;
    }
    
    public void setEstimatedHours(String estimatedHours) {
        this.estimatedHours = estimatedHours;
    }
    public Set<NoteAttachement> getNoteAttachements() {
        return this.noteAttachements;
    }
    
    public void setNoteAttachements(Set<NoteAttachement> noteAttachements) {
        this.noteAttachements = noteAttachements;
    }




}


