package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA



/**
 * Participant generated by hbm2java
 */
public class Participant  implements java.io.Serializable {


     private int participantId;
     private Role role;
     private User user;
     private Project project;

    public Participant() {
    }

    public Participant(int participantId, Role role, User user, Project project) {
       this.participantId = participantId;
       this.role = role;
       this.user = user;
       this.project = project;
    }
   
    public int getParticipantId() {
        return this.participantId;
    }
    
    public void setParticipantId(int participantId) {
        this.participantId = participantId;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }




}


