package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Permission generated by hbm2java
 */
public class Permission  implements java.io.Serializable {


     private Integer permissionId;
     private ItpComponent itpComponent;
     private String permissionName;
     private String permissionDescription;
     private boolean canInsert;
     private boolean canModifiy;
     private boolean canRemove;
     private boolean canView;
     private Set<Role> roles = new HashSet<Role>(0);

    public Permission() {
    }

	
    public Permission(ItpComponent itpComponent, boolean canInsert, boolean canModifiy, boolean canRemove, boolean canView) {
        this.itpComponent = itpComponent;
        this.canInsert = canInsert;
        this.canModifiy = canModifiy;
        this.canRemove = canRemove;
        this.canView = canView;
    }
    public Permission(ItpComponent itpComponent, String permissionName, String permissionDescription, boolean canInsert, boolean canModifiy, boolean canRemove, boolean canView, Set<Role> roles) {
       this.itpComponent = itpComponent;
       this.permissionName = permissionName;
       this.permissionDescription = permissionDescription;
       this.canInsert = canInsert;
       this.canModifiy = canModifiy;
       this.canRemove = canRemove;
       this.canView = canView;
       this.roles = roles;
    }
   
    public Integer getPermissionId() {
        return this.permissionId;
    }
    
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
    public ItpComponent getItpComponent() {
        return this.itpComponent;
    }
    
    public void setItpComponent(ItpComponent itpComponent) {
        this.itpComponent = itpComponent;
    }
    public String getPermissionName() {
        return this.permissionName;
    }
    
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }
    public String getPermissionDescription() {
        return this.permissionDescription;
    }
    
    public void setPermissionDescription(String permissionDescription) {
        this.permissionDescription = permissionDescription;
    }
    public boolean isCanInsert() {
        return this.canInsert;
    }
    
    public void setCanInsert(boolean canInsert) {
        this.canInsert = canInsert;
    }
    public boolean isCanModifiy() {
        return this.canModifiy;
    }
    
    public void setCanModifiy(boolean canModifiy) {
        this.canModifiy = canModifiy;
    }
    public boolean isCanRemove() {
        return this.canRemove;
    }
    
    public void setCanRemove(boolean canRemove) {
        this.canRemove = canRemove;
    }
    public boolean isCanView() {
        return this.canView;
    }
    
    public void setCanView(boolean canView) {
        this.canView = canView;
    }
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }




}


