package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Priority generated by hbm2java
 */
public class Priority  implements java.io.Serializable {


     private Integer priorityId;
     private String priorityName;
     private String priorityDescription;
     private int priorityOrder;
     private String iconFilename;
     private Set<Project> projects = new HashSet<Project>(0);
     private Set<Note> notes = new HashSet<Note>(0);

    public Priority() {
    }

	
    public Priority(String priorityDescription, int priorityOrder) {
        this.priorityDescription = priorityDescription;
        this.priorityOrder = priorityOrder;
    }
    public Priority(String priorityName, String priorityDescription, int priorityOrder, String iconFilename, Set<Project> projects, Set<Note> notes) {
       this.priorityName = priorityName;
       this.priorityDescription = priorityDescription;
       this.priorityOrder = priorityOrder;
       this.iconFilename = iconFilename;
       this.projects = projects;
       this.notes = notes;
    }
   
    public Integer getPriorityId() {
        return this.priorityId;
    }
    
    public void setPriorityId(Integer priorityId) {
        this.priorityId = priorityId;
    }
    public String getPriorityName() {
        return this.priorityName;
    }
    
    public void setPriorityName(String priorityName) {
        this.priorityName = priorityName;
    }
    public String getPriorityDescription() {
        return this.priorityDescription;
    }
    
    public void setPriorityDescription(String priorityDescription) {
        this.priorityDescription = priorityDescription;
    }
    public int getPriorityOrder() {
        return this.priorityOrder;
    }
    
    public void setPriorityOrder(int priorityOrder) {
        this.priorityOrder = priorityOrder;
    }
    public String getIconFilename() {
        return this.iconFilename;
    }
    
    public void setIconFilename(String iconFilename) {
        this.iconFilename = iconFilename;
    }
    public Set<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }




}


