package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ProjectCategory generated by hbm2java
 */
public class ProjectCategory  implements java.io.Serializable {


     private Integer projectCategoryId;
     private String projectCategoryName;
     private String projectCategoryDescription;
     private Set<Project> projects = new HashSet<Project>(0);

    public ProjectCategory() {
    }

    public ProjectCategory(String projectCategoryName, String projectCategoryDescription, Set<Project> projects) {
       this.projectCategoryName = projectCategoryName;
       this.projectCategoryDescription = projectCategoryDescription;
       this.projects = projects;
    }
   
    public Integer getProjectCategoryId() {
        return this.projectCategoryId;
    }
    
    public void setProjectCategoryId(Integer projectCategoryId) {
        this.projectCategoryId = projectCategoryId;
    }
    public String getProjectCategoryName() {
        return this.projectCategoryName;
    }
    
    public void setProjectCategoryName(String projectCategoryName) {
        this.projectCategoryName = projectCategoryName;
    }
    public String getProjectCategoryDescription() {
        return this.projectCategoryDescription;
    }
    
    public void setProjectCategoryDescription(String projectCategoryDescription) {
        this.projectCategoryDescription = projectCategoryDescription;
    }
    public Set<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }




}


