package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ProjectStatus generated by hbm2java
 */
public class ProjectStatus  implements java.io.Serializable {


     private Integer projectStatusId;
     private String projectStatusName;
     private String projectStatusDescription;
     private Set<Project> projects = new HashSet<Project>(0);

    public ProjectStatus() {
    }

    public ProjectStatus(String projectStatusName, String projectStatusDescription, Set<Project> projects) {
       this.projectStatusName = projectStatusName;
       this.projectStatusDescription = projectStatusDescription;
       this.projects = projects;
    }
   
    public Integer getProjectStatusId() {
        return this.projectStatusId;
    }
    
    public void setProjectStatusId(Integer projectStatusId) {
        this.projectStatusId = projectStatusId;
    }
    public String getProjectStatusName() {
        return this.projectStatusName;
    }
    
    public void setProjectStatusName(String projectStatusName) {
        this.projectStatusName = projectStatusName;
    }
    public String getProjectStatusDescription() {
        return this.projectStatusDescription;
    }
    
    public void setProjectStatusDescription(String projectStatusDescription) {
        this.projectStatusDescription = projectStatusDescription;
    }
    public Set<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }




}


