package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer roleId;
     private Permission permission;
     private String roleName;
     private String roleDescription;
     private Set<Participant> participants = new HashSet<Participant>(0);

    public Role() {
    }

	
    public Role(Permission permission) {
        this.permission = permission;
    }
    public Role(Permission permission, String roleName, String roleDescription, Set<Participant> participants) {
       this.permission = permission;
       this.roleName = roleName;
       this.roleDescription = roleDescription;
       this.participants = participants;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public Permission getPermission() {
        return this.permission;
    }
    
    public void setPermission(Permission permission) {
        this.permission = permission;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getRoleDescription() {
        return this.roleDescription;
    }
    
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }
    public Set<Participant> getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(Set<Participant> participants) {
        this.participants = participants;
    }




}


