package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Session generated by hbm2java
 */
public class Session  implements java.io.Serializable {


     private Integer sessionId;
     private SessionStatus sessionStatus;
     private Date sessionStartTime;
     private Date sessionEndTime;
     private Boolean loginSuccess;
     private String username;
     private String ipAddress;
     private String httpHeader;

    public Session() {
    }

	
    public Session(SessionStatus sessionStatus, Date sessionStartTime, Date sessionEndTime) {
        this.sessionStatus = sessionStatus;
        this.sessionStartTime = sessionStartTime;
        this.sessionEndTime = sessionEndTime;
    }
    public Session(SessionStatus sessionStatus, Date sessionStartTime, Date sessionEndTime, Boolean loginSuccess, String username, String ipAddress, String httpHeader) {
       this.sessionStatus = sessionStatus;
       this.sessionStartTime = sessionStartTime;
       this.sessionEndTime = sessionEndTime;
       this.loginSuccess = loginSuccess;
       this.username = username;
       this.ipAddress = ipAddress;
       this.httpHeader = httpHeader;
    }
   
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }
    public SessionStatus getSessionStatus() {
        return this.sessionStatus;
    }
    
    public void setSessionStatus(SessionStatus sessionStatus) {
        this.sessionStatus = sessionStatus;
    }
    public Date getSessionStartTime() {
        return this.sessionStartTime;
    }
    
    public void setSessionStartTime(Date sessionStartTime) {
        this.sessionStartTime = sessionStartTime;
    }
    public Date getSessionEndTime() {
        return this.sessionEndTime;
    }
    
    public void setSessionEndTime(Date sessionEndTime) {
        this.sessionEndTime = sessionEndTime;
    }
    public Boolean getLoginSuccess() {
        return this.loginSuccess;
    }
    
    public void setLoginSuccess(Boolean loginSuccess) {
        this.loginSuccess = loginSuccess;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public String getHttpHeader() {
        return this.httpHeader;
    }
    
    public void setHttpHeader(String httpHeader) {
        this.httpHeader = httpHeader;
    }




}


