package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SessionStatus generated by hbm2java
 */
public class SessionStatus  implements java.io.Serializable {


     private Integer sessionStatusId;
     private String sessionStatusName;
     private String sessionStatusDescription;
     private Set<Session> sessions = new HashSet<Session>(0);

    public SessionStatus() {
    }

	
    public SessionStatus(String sessionStatusName, String sessionStatusDescription) {
        this.sessionStatusName = sessionStatusName;
        this.sessionStatusDescription = sessionStatusDescription;
    }
    public SessionStatus(String sessionStatusName, String sessionStatusDescription, Set<Session> sessions) {
       this.sessionStatusName = sessionStatusName;
       this.sessionStatusDescription = sessionStatusDescription;
       this.sessions = sessions;
    }
   
    public Integer getSessionStatusId() {
        return this.sessionStatusId;
    }
    
    public void setSessionStatusId(Integer sessionStatusId) {
        this.sessionStatusId = sessionStatusId;
    }
    public String getSessionStatusName() {
        return this.sessionStatusName;
    }
    
    public void setSessionStatusName(String sessionStatusName) {
        this.sessionStatusName = sessionStatusName;
    }
    public String getSessionStatusDescription() {
        return this.sessionStatusDescription;
    }
    
    public void setSessionStatusDescription(String sessionStatusDescription) {
        this.sessionStatusDescription = sessionStatusDescription;
    }
    public Set<Session> getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Set<Session> sessions) {
        this.sessions = sessions;
    }




}


