package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA



/**
 * State generated by hbm2java
 */
public class State  implements java.io.Serializable {


     private String stateCode;
     private String stateName;

    public State() {
    }

	
    public State(String stateCode) {
        this.stateCode = stateCode;
    }
    public State(String stateCode, String stateName) {
       this.stateCode = stateCode;
       this.stateName = stateName;
    }
   
    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }




}


