package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TicketHeader generated by hbm2java
 */
public class TicketHeader  implements java.io.Serializable {


     private Integer ticketHeaderId;
     private String ticketSubject;
     private String ticketSummary;
     private Date ticketRequestDateTime;
     private String requestorUsername;
     private String requesteeUsername;
     private String priorityId;
     private int tickectStatusId;
     private int isOpen;
     private Date dateClosed;
     private Date dateReopended;

    public TicketHeader() {
    }

	
    public TicketHeader(Date ticketRequestDateTime, String requestorUsername, String requesteeUsername, String priorityId, int tickectStatusId, int isOpen) {
        this.ticketRequestDateTime = ticketRequestDateTime;
        this.requestorUsername = requestorUsername;
        this.requesteeUsername = requesteeUsername;
        this.priorityId = priorityId;
        this.tickectStatusId = tickectStatusId;
        this.isOpen = isOpen;
    }
    public TicketHeader(String ticketSubject, String ticketSummary, Date ticketRequestDateTime, String requestorUsername, String requesteeUsername, String priorityId, int tickectStatusId, int isOpen, Date dateClosed, Date dateReopended) {
       this.ticketSubject = ticketSubject;
       this.ticketSummary = ticketSummary;
       this.ticketRequestDateTime = ticketRequestDateTime;
       this.requestorUsername = requestorUsername;
       this.requesteeUsername = requesteeUsername;
       this.priorityId = priorityId;
       this.tickectStatusId = tickectStatusId;
       this.isOpen = isOpen;
       this.dateClosed = dateClosed;
       this.dateReopended = dateReopended;
    }
   
    public Integer getTicketHeaderId() {
        return this.ticketHeaderId;
    }
    
    public void setTicketHeaderId(Integer ticketHeaderId) {
        this.ticketHeaderId = ticketHeaderId;
    }
    public String getTicketSubject() {
        return this.ticketSubject;
    }
    
    public void setTicketSubject(String ticketSubject) {
        this.ticketSubject = ticketSubject;
    }
    public String getTicketSummary() {
        return this.ticketSummary;
    }
    
    public void setTicketSummary(String ticketSummary) {
        this.ticketSummary = ticketSummary;
    }
    public Date getTicketRequestDateTime() {
        return this.ticketRequestDateTime;
    }
    
    public void setTicketRequestDateTime(Date ticketRequestDateTime) {
        this.ticketRequestDateTime = ticketRequestDateTime;
    }
    public String getRequestorUsername() {
        return this.requestorUsername;
    }
    
    public void setRequestorUsername(String requestorUsername) {
        this.requestorUsername = requestorUsername;
    }
    public String getRequesteeUsername() {
        return this.requesteeUsername;
    }
    
    public void setRequesteeUsername(String requesteeUsername) {
        this.requesteeUsername = requesteeUsername;
    }
    public String getPriorityId() {
        return this.priorityId;
    }
    
    public void setPriorityId(String priorityId) {
        this.priorityId = priorityId;
    }
    public int getTickectStatusId() {
        return this.tickectStatusId;
    }
    
    public void setTickectStatusId(int tickectStatusId) {
        this.tickectStatusId = tickectStatusId;
    }
    public int getIsOpen() {
        return this.isOpen;
    }
    
    public void setIsOpen(int isOpen) {
        this.isOpen = isOpen;
    }
    public Date getDateClosed() {
        return this.dateClosed;
    }
    
    public void setDateClosed(Date dateClosed) {
        this.dateClosed = dateClosed;
    }
    public Date getDateReopended() {
        return this.dateReopended;
    }
    
    public void setDateReopended(Date dateReopended) {
        this.dateReopended = dateReopended;
    }




}


