package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TicketDetails generated by hbm2java
 */
public class TicketDetails  implements java.io.Serializable {


     private Integer ticketDetailsId;
     private String ticketResponese;
     private Date responseDateTime;
     private String username;
     private int isReceivedResponse;

    public TicketDetails() {
    }

    public TicketDetails(String ticketResponese, Date responseDateTime, String username, int isReceivedResponse) {
       this.ticketResponese = ticketResponese;
       this.responseDateTime = responseDateTime;
       this.username = username;
       this.isReceivedResponse = isReceivedResponse;
    }
   
    public Integer getTicketDetailsId() {
        return this.ticketDetailsId;
    }
    
    public void setTicketDetailsId(Integer ticketDetailsId) {
        this.ticketDetailsId = ticketDetailsId;
    }
    public String getTicketResponese() {
        return this.ticketResponese;
    }
    
    public void setTicketResponese(String ticketResponese) {
        this.ticketResponese = ticketResponese;
    }
    public Date getResponseDateTime() {
        return this.responseDateTime;
    }
    
    public void setResponseDateTime(Date responseDateTime) {
        this.responseDateTime = responseDateTime;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public int getIsReceivedResponse() {
        return this.isReceivedResponse;
    }
    
    public void setIsReceivedResponse(int isReceivedResponse) {
        this.isReceivedResponse = isReceivedResponse;
    }




}


