package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA



/**
 * TicketAttachement generated by hbm2java
 */
public class TicketAttachement  implements java.io.Serializable {


     private Integer ticketAttachement;
     private int fileRecordId;
     private int ticketDetailId;

    public TicketAttachement() {
    }

    public TicketAttachement(int fileRecordId, int ticketDetailId) {
       this.fileRecordId = fileRecordId;
       this.ticketDetailId = ticketDetailId;
    }
   
    public Integer getTicketAttachement() {
        return this.ticketAttachement;
    }
    
    public void setTicketAttachement(Integer ticketAttachement) {
        this.ticketAttachement = ticketAttachement;
    }
    public int getFileRecordId() {
        return this.fileRecordId;
    }
    
    public void setFileRecordId(int fileRecordId) {
        this.fileRecordId = fileRecordId;
    }
    public int getTicketDetailId() {
        return this.ticketDetailId;
    }
    
    public void setTicketDetailId(int ticketDetailId) {
        this.ticketDetailId = ticketDetailId;
    }




}


