package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA



/**
 * TicketAction generated by hbm2java
 */
public class TicketAction  implements java.io.Serializable {


     private Integer ticketAction;
     private String ticketActionName;
     private String ticketActionDescription;

    public TicketAction() {
    }

	
    public TicketAction(String ticketActionName) {
        this.ticketActionName = ticketActionName;
    }
    public TicketAction(String ticketActionName, String ticketActionDescription) {
       this.ticketActionName = ticketActionName;
       this.ticketActionDescription = ticketActionDescription;
    }
   
    public Integer getTicketAction() {
        return this.ticketAction;
    }
    
    public void setTicketAction(Integer ticketAction) {
        this.ticketAction = ticketAction;
    }
    public String getTicketActionName() {
        return this.ticketActionName;
    }
    
    public void setTicketActionName(String ticketActionName) {
        this.ticketActionName = ticketActionName;
    }
    public String getTicketActionDescription() {
        return this.ticketActionDescription;
    }
    
    public void setTicketActionDescription(String ticketActionDescription) {
        this.ticketActionDescription = ticketActionDescription;
    }




}


