package com.itp.dao.entity;
// Generated Jun 17, 2011 1:34:28 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Version generated by hbm2java
 */
public class Version  implements java.io.Serializable {


     private Integer versionId;
     private Project project;
     private String versionName;
     private String versionDescription;
     private String versionSchedule;
     private Date releaseDate;

    public Version() {
    }

	
    public Version(Project project, Date releaseDate) {
        this.project = project;
        this.releaseDate = releaseDate;
    }
    public Version(Project project, String versionName, String versionDescription, String versionSchedule, Date releaseDate) {
       this.project = project;
       this.versionName = versionName;
       this.versionDescription = versionDescription;
       this.versionSchedule = versionSchedule;
       this.releaseDate = releaseDate;
    }
   
    public Integer getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getVersionName() {
        return this.versionName;
    }
    
    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }
    public String getVersionDescription() {
        return this.versionDescription;
    }
    
    public void setVersionDescription(String versionDescription) {
        this.versionDescription = versionDescription;
    }
    public String getVersionSchedule() {
        return this.versionSchedule;
    }
    
    public void setVersionSchedule(String versionSchedule) {
        this.versionSchedule = versionSchedule;
    }
    public Date getReleaseDate() {
        return this.releaseDate;
    }
    
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }




}


