package com.itp.jsp.WEB_002dINF.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath());
      out.write("/WEB-INF/css/Style.css\" />\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<title>Information Technology Portal</title>\r\n</head>\r\n\r\n\r\n<body>\r\n<tr>\r\n\t<td>\r\n    \t<table cellpadding=\"5\" cellspacing=\"5\" width=\"100%\">\r\n                 <tr>\r\n                    <td>\r\n                        <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n                            <tr>\r\n                                <td class=\"header\">\r\n                                    <table align=\"right\">\r\n                                        <tr>\r\n                                            <td class=\"nameHover\">\r\n                                            Name|        \t\r\n                                            </td>\r\n                                            <td>\r\n                                            <input type=\"text\" size=\"30\" value=\"Quick Search\" />\r\n                                            </td>\r\n                                        </tr>\r\n                                    </table>\r\n");
      out.write("                                </td>\r\n                                \r\n                            </tr>\r\n                            <tr>\r\n                            <td class=\"menu\">\r\n                                <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" height=\"25px\">\r\n                                    <tr>\r\n                                    \t<td width=\"1%\"></td>\r\n                                        <td width=\"5%\" class=\"menuHover\">\r\n                                            Dashboards| \r\n                                        </td>\r\n                                        <td width=\"4%\" class=\"menuHover\">\r\n                                            Projects| \r\n                                      </td>\r\n                                        <td width=\"3%\" class=\"menuHover\">\r\n                                            Issues| \r\n                                        </td class=\"menuHover\">\r\n                                        <td width=\"6%\" class=\"menuHover\">\r\n                                            Administration| \r\n");
      out.write("                                        </td>\r\n                                        <td width=\"77%\"></td>\r\n                                        <td width=\"5%\" align=\"right\" class=\"menuHover\">\r\n                                            Create Issue\r\n                                        </td>\r\n                                    </tr>\r\n                                </table>\r\n                            </td>\r\n                                \r\n                            </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td valign=\"top\">\r\n                        <table style=\"border:2px solid #D2D2D2\" width=\"99%\" align=\"center\" cellpadding=\"2\" cellspacing=\"2\" bgcolor=\"#FFFFFF\">\r\n                            <tr>\r\n                                <td width=\"50%\">\r\n                                    <table style=\"border:1px solid #D2D2D2\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\r\n                                    \t<tr>\r\n");
      out.write("                                        \t<td class=\"headerBox\">\r\n                                            \tIntroduction\r\n                                          </td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                        \t<td style=\"font-size:12px; font-family:Arial, Helvetica, sans-serif\">\r\n                                            \tThanks for choosing JIRA.<br/>\r\n                                                Welcome to JIRA â the easy way to help your team track and deliver projects.<br/><br/>\r\n                                                \r\n                                                Where do I start?<br/>\r\n                                                Learn more about configuring JIRA with the JIRA 101 guide.<br/><br/>\r\n                                                \r\n                                                Get up to speed with an in-depth, interactive Atlassian training course.<br/><br/>\r\n                                                \r\n");
      out.write("                                                You can customize this text in the Administration section.<br/><br/>\r\n                                                \r\n                                                Agile project management for JIRA<br/>\r\n                                                The GreenHopper plugin for JIRA provides agile project management and assists with the introduction of agile to your team. Get started with the GreenHopper 101 guide.\r\n                                          </td>\r\n                                        </tr>\r\n                                    </table>\r\n                                </td>\r\n                                <td width=\"50%\">\r\n                                \t<table width=\"100%\">\r\n                                    \t<tr>\r\n                                        \t<td>\r\n                                            \t<table style=\"border:1px solid #D2D2D2\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\" height=\"120\">\r\n                                                    <tr>\r\n");
      out.write("                                                        <td class=\"headerBox\">\r\n                                                            Assigned to Me</td>\r\n                                                    </tr>\r\n                                                    <tr>\r\n                                                        <td>\r\n                                                            No matching issues found.\r\n                                                        </td>\r\n                                                    </tr>\r\n                                                </table>\t\r\n                                            </td>\r\n                                         </tr>\r\n                                         <tr>\r\n                                        \t<td>\r\n                                            \t<table style=\"border:1px solid #D2D2D2\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\r\n                                                    <tr>\r\n                                                        <td class=\"headerBox\" colspan=\"2\">\r\n");
      out.write("                                                            Favorite Filters</td>\r\n                                                    </tr>\r\n                                                    <tr>\r\n                                                        <td colspan=\"2\">\r\n                                                            You have no filters at the moment<br /><br />\r\n                                                        </td>\r\n                                                    </tr>\r\n                                                    <tr>\r\n                                                    \t<td width=\"14%\">\r\n                                                        \tCreate Filter\r\n                                                        </td>\r\n                                                        <td width=\"86%\">\r\n                                                        \tManage Filter\r\n                                                        </td>\r\n                                                    </tr>\r\n");
      out.write("                                                </table>\t\r\n                                            </td>\r\n                                         </tr>\r\n                                        \r\n                                    </table>\r\n                                    \r\n                              </td>\r\n                                \r\n                            </tr>\r\n                            <tr>\r\n                                <td>\r\n                                    <table style=\"border:1px solid #D2D2D2\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\" height=\"120\">\r\n                                    \t<tr>\r\n                                        \t<td class=\"headerBox\">\r\n                                            Activity Stream\r\n                                            </td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                        \t<td>\r\n                                            Crimmy<br /><br />\r\n");
      out.write("                                            </td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                        \t<td>No activity was found</td>\r\n                                        </tr>\r\n                                    </table>\r\n                                </td>\r\n                                <td>\r\n                                    <table style=\"border:1px solid #D2D2D2\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\r\n                                    \t<tr>\r\n                                        \t<td width=\"9%\" class=\"headerBox\" colspan=\"2\">\r\n                                            Admin\r\n                                            </td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                        \t<td valign=\"top\" style=\"font-weight:bold\">\r\n                                              Projects <br />\r\n                                              Users<br />\r\n");
      out.write("                                              Data<br />\r\n                                              Setup <br />\r\n                                              Licence <br />\r\n                                              <br />\r\n\t\t\t\t\t\t\t\t\t\t\t  <br />\r\n                                              Database          \r\n                                            </td>\r\n                                            <td width=\"91%\">\r\n                                               View all or create new<br />\r\n                                               Browse users, groups or create a new user.<br />\r\n                                               Restore or backup JIRA data as XML<br />\r\n                                               Configure JIRA or modify global permissions<br />\r\n                                               JIRA: Evaluation<br />\r\n                                               (view details)<br />\r\n\t\t\t\t\t\t\t\t\t\t\t   (Expires in 22 days, 12 hours on 17/Jun/11)<br />\r\n                                               You are using HSQL DB, which is an in-memory database and susceptible to corruption when abnormally terminated. DO NOT USE THIS IN A\r\n");
      out.write("                                               PRODUCTION SYSTEM. Instead we recommend using an external database, for a list of supported databases please see our documentation\r\n                                            </td>\r\n                                        </tr>\r\n                                    </table>\r\n                                </td>\r\n                            </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                \t<td align=\"center\" style=\"font-size:11px; font-family:Arial, Helvetica, sans-serif\">\r\n                    \tAtlassian JIRA (v4.3.3#617-r149616) | Report a problem                    \r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                \t<td align=\"center\" style=\"font-size:12px; font-family:Arial, Helvetica, sans-serif\">\r\n                    \tPOWERED BY A FREE ATLASSIAN JIRA EVALUATION LICENSE. PLEASE CONSIDER PURCHASING IT TODAY.                    \r\n                    </td>\r\n");
      out.write("                </tr>\r\n        </table>\r\n    </td>\r\n</tr>\r\n\r\n\r\n</body>\r\n</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
