package com.itp.jsp.WEB_002dINF.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class users_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div>\n    <table class=\"componentStyle\" width=\"100%\" cellpadding=\"10\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\n\t<tr>\n\t\t<td class=\"headerBox\">\n\t\t\tManage User\n\t\t</td>\n    </tr>\n\t<tr>\n        <td>\n<div >Advanced Search\n                                            <table width=\"100%\"   cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\n                                                    \n                                                    \n                                                    <tr>\n                                                        <td colspan=\"2\" style=\"background-color:#215F92\"   height=\"2\"></td>\n                                                      \n                                                    </tr>\n                                                     <tr>\n                                                        <td colspan=\"2\" style=\"border:#215F92 solid 1px \">\n                                                            \t<table width=\"100%\" border=\"0\">\n                                                                  <tr>\n");
      out.write("                                                                    <td width=\"100%\">Search:&nbsp;\n                                                                        <input type=\"text\" size=\"30\" value=\"Quick Search\" />\n                                                                      <!-- &nbsp;&nbsp; Search by:&nbsp; <select name=\"goto\" class=\"\"  id=\"goto\" onchange=\"gotopage('goto2')\">\n                                                                      <option value=\"1\">Name</option>\n                                                                      <option value=\"2\">Roles</option>\n                                                                      <option value=\"2\">Project</option>\n                                                                    </select>\n                                                                    &nbsp;&nbsp;Order:\n                                                                     \n                                                                      <select name=\"goto\" class=\"\"  id=\"goto\" onchange=\"gotopage('goto2')\">\n");
      out.write("                                                                      <option value=\"1\">Ascending</option>\n                                                                      <option value=\"2\">Descending</option>\n                                                                     \n                                                                    </select>-->\n                                                                      <span style=\"text-align:right\">&nbsp;&nbsp;&nbsp;&nbsp;\n                                                                      <input type=\"button\" value=\"Search\" />\n                                                                    </span></td>\n                                                                  </tr>\n                                                                </table></td>\n                                                      \n                                                    </tr>\n                                                </table>\n                                            </div>\n");
      out.write("            ");
      out.write("\n<div>\n<br /><br />\n                                            <div class=\"blue_links\"><a href=\"javascript:displayUserDiv(1);\"   style=\"font-size:13px; vertical-align:middle;padding: .4em 1em .4em 10px;text-decoration: none;position: relative;\" class=\"ui-state-default ui-corner-all\"><b><img src=\"");
      out.print( request.getContextPath());
      out.write("/images/add_16.png\" width=\"16\" height=\"16\" alt=\"Add\"  border=\"0\"/> Create New User Account</b></a></div>\n                                            <br /><br />\n  <table width=\"100%\" class=\"tableStyle\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\n  \n                    <tr>\n                        <th width=\"18%\">User Name</th>\n                        <th width=\"18%\">User Roles</th>\n                        <th width=\"36%\">Projects</th>\n                        <th width=\"10%\">Active</th>\n                        <th width=\"18%\">Action</th>\n                    </tr>\n                    <tr>\n                        <td><a href=\"#\">(dary1)</a></td>\n                        <td><a href=\"#\">(admin)</a></td>\n                        <td>(pName)</td>\n                        <td align=\"center\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/icon_check.png\" width=\"23\" height=\"18\" alt=\"True\" /></td>\n                        <td align=\"center\"><a href=\"#\">Edit</a>&nbsp;|&nbsp;<a href=\"#\">Delete</a>&nbsp;|&nbsp;<a href=\"#\">Deactivate</a></td>\n                        \n                    </tr>  \n                </table>\n                <table width=\"100%\">\n                <tr>\n                        <td align=\"left\"> Total result(s) found: 1</td>\n                                                     <td align=\"right\" class=\"right blue_links\"><a href=\"javascript:loadPrevPostedJobs();\" id=\"prevs2\">&laquo; PREV</a>  |  <a href=\"javascript:loadNextPostedJobs();\" id=\"next2\">NEXT &raquo;</a> | Go to \n                                                 \t\t<select  id=\"goto2\" class=\"blue_links\" onchange=\"gotopage('goto2')\">\n                                                 \t\t\t\t<option value=\"1\">1</option>\n                                                                <option value=\"2\">2</option>\n                                                        </select>\n");
      out.write("                                                        <input type=\"hidden\" id=\"max\" value=\"\"/>  <input type=\"hidden\" id=\"index\" value=\"0\"/>\n                                                    </td>\n                </tr>\n                </table>\n            </div>\n        </td>\n\t</tr>\n    <tr>\n    \t<td>\n        \t<br />\t\n                                            <div id=\"newUserDIv\" style=\"width:800px; display:none\">\n                                                <table   cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\" >\n                                                    <tr>\n                                                        <th class=\"tabBox\" width=\"25%\" align=\"left\">\n                                                            New  Account\n                                                     </th>\n                                                      <th  width=\"75%\" >\n                                                           \n                                                      </th>\n                                                    </tr>\n");
      out.write("                                                    \n                                                    <tr>\n                                                        <td colspan=\"2\" style=\"background-color:#215F92\"   height=\"2\"></td>\n                                                      \n                                                    </tr>\n                                                     <tr>\n                                                        <td colspan=\"2\" style=\"border:#215F92 solid 1px ;padding:10px\" >\n                                                            \t<table width=\"100%\" border=\"0\">\n                                                                  <tr>\n                                                                    <td width=\"24%\" >&nbsp;</td>\n                                                                    <td colspan=\"3\">&nbsp;</td>\n                                                                    \n                                                                  </tr>\n                                                                  <tr>\n");
      out.write("                                                                    <td>Last Name:</td>\n                                                                    <td width=\"39%\"><input type=\"text\"  cols=\"80\"    /></td>\n                                                                    <td width=\"15%\">First Name:</td>\n                                                                    <td width=\"21%\" align=\"right\"><input type=\"text\"  cols=\"80\"    /></td>\n                                                                   \n                                                                  </tr>\n                                                                  <tr>\n                                                                    <td>User Name::</td>\n                                                                    <td><input type=\"text\"  cols=\"80\"    /></td>\n                                                                    <td width=\"15%\">Email:</td>\n                                                                    <td width=\"21%\" align=\"right\"><input type=\"text\"  cols=\"80\"    /></td>\n");
      out.write("                                                                  \n                                                                  </tr>\n                                                                  <tr>\n                                                                    <td>Default Password::</td>\n                                                                    <td><input type=\"text\"  cols=\"80\"    /></td>\n                                                                    <td width=\"15%\">Phone No.:</td>\n                                                                    <td width=\"21%\" align=\"right\"><input type=\"text\"  cols=\"80\"    /></td>\n                                                                   \n                                                                  </tr>\n                                                                  <tr>\n                                                                    <td>Re-type Password:</td>\n                                                                    <td><input type=\"text\"  cols=\"80\"    /></td>\n");
      out.write("                                                                    <td width=\"15%\">Mobile No.:</td>\n                                                                    <td width=\"21%\" align=\"right\"><input type=\"text\"  cols=\"80\"    /></td>\n                                                                  </tr>\n                                                                  <tr>\n                                                                    <td>Add User Roles:</td>\n                                                                    <td colspan=\"3\"><select name=\"goto\" class=\"\"  id=\"goto\" onchange=\"gotopage('goto2')\">\n                                                                      <option value=\"1\">Select Roles</option>\n                                                                      <option value=\"2\">admin</option>\n                                                                    </select></td>\n                                                                  </tr>\n                                                                  \n");
      out.write("                                                                  <tr>\n                                                                    <td>&nbsp;</td>\n                                                                    <td colspan=\"3\">&nbsp;</td>\n                                                                  </tr>\n                                                                  <tr>\n                                                                    <td>&nbsp;</td>\n                                                                   \n                                                                    <td colspan=\"3\" style=\"text-align:right\"><input type=\"button\" value=\"Save\" />&nbsp;&nbsp;&nbsp;<input type=\"button\" value=\"Cancel\"  onclick=\"javascript:displayUserDiv(0);\"/></td>\n                                                                    <td width=\"1%\">&nbsp;</td>\n                                                                  </tr>\n                                                                </table>\n");
      out.write("\n                                                        </td>\n                                                      \n                                                    </tr>\n                                                </table>\n                                            </div>\n        </td>\n    </tr>\n</table>\n</div>\n<script language='javascript'> \n  function displayUserDiv( bit){\n      if (bit==1)\n           document.getElementById('newUserDIv').style.display='block';\n      else\n           document.getElementById('newUserDIv').style.display='none';\n  }\n</script>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
